version: '3'

services:
  frontend:
    build:
      context: ./frontend  # Set the build context to the frontend folder
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

  backend:
    build:
      context: ./backend  # Set the build context to the backend folder
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    build:
      context: ./backend  # Set the build context to the db folder
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
